Repository Persinus/HotelManagementAPI, pull requests merged in 2025-06, with the labels that each got.

#34 Phân chia DTOs và code thêm Controller
  .gitignore
  Controllers/KhachHangController.cs
  Controllers/NhanVien/NhanVienController.cs
  Controllers/NhanVien/NhanVien_BaoCaoController.cs
  Controllers/NhanVien/NhanVien_DichVuQuanLyController.cs
  Controllers/NhanVien/NhanVien_GiamGiaController.cs
  Controllers/NhanVien/NhanVien_PhongQuanLyController.cs
  Controllers/NhanVienController.cs
  Controllers/QuanTriVien/QuanTriVien_HeThongController.cs
  Controllers/TatCaTruyCapController.cs
  Controllers/XacThucController.cs
  DTOs/Chung/LoginDTO.cs
  DTOs/Chung/NguoiDungDTO.cs
  DTOs/Chung/ResetPasswordDTO.cs
  DTOs/HienThiTatCaXem/DichVuDTO.cs
  DTOs/HienThiTatCaXem/FeedBackDTO.cs
  DTOs/HienThiTatCaXem/GiamGiaDTO.cs
  DTOs/HienThiTatCaXem/PhongAnhDTO.cs
  DTOs/HienThiTatCaXem/PhongDTO.cs
  DTOs/HienThiTatCaXem/PhongDetailsDTO.cs
  DTOs/HienThiTatCaXem/TienNghiDTO.cs
  DTOs/KhachHang/KhachHangChiTietHoaDon.cs
  DTOs/KhachHang/KhachHangDatDichVuDTO.cs
  DTOs/KhachHang/KhachHangDatPhongDTO.cs
  DTOs/KhachHang/KhachHangHoaDonDTO.cs
  DTOs/KhachHang/KhachHangLichSuGiaoDichDTO.cs
  DTOs/KhachHang/KhachHangThanhToanDTO.cs
  DTOs/NhanVien/BaoCaoDTO.cs
  DTOs/NhanVien/ChiTietBaoCaoDTO.cs
  DTOs/NhanVien/NhanVienSuaDichVuDTO.cs
  DTOs/NhanVien/NhanVienSuaPhongAnhPutDTO.cs
  DTOs/NhanVien/NhanVienSuaPhongGiamGiaDTO.cs
  DTOs/NhanVien/NhanVienSuaPhongTienNghiDTO.cs
  DTOs/QuanTriVien/QuanTriVienSuaRoleDTO.cs
  DTOs/QuanTriVien/QuanTriVienThem1DichVuDTO.cs
  DTOs/QuanTriVien/QuanTriVienThem1PhongDTO.cs
  DTOs/QuanTriVien/QuanTriVienThem1TienNghiDTO.cs
  DTOs/QuanTriVien/QuanTriVienThemAnhDTO.cs
  DTOs/QuanTriVien/QuanTriVienThemMaGiamGiaDTO.cs
  DTOs/QuanTriVien/QuanTriVienThemNhieuDichVu.cs
  DTOs/QuanTriVien/QuanTriVienThemNhieuTienNghiDTO.cs
  HotelManagementAPI.csproj
  Program.cs
  TaoHoaDonRequestDTO.cs
  Validators/HoaDonDTOValidator.cs
  Validators/PhongDetailsDTOValidator.cs
  Validators/ThanhToanDTOValidation.cs
  Validators/ThanhToanDTOValidator.cs
Labels: size/XXL

#35 Thêm Thanh toán - Làm chơi chơi
  Controllers/VnPayController.cs
  DTOs/KhachHang/TaoHoaDonRequestDTO.cs
  HotelManagementAPI.csproj
  Models/PaymentRequest.cs
  Models/PaymentResponse.cs
  Models/PaymentResult.cs
  Models/VnpayCallbackRequest.cs
  Program.cs
  SQLQuery2.sql
  Services/IVnpayService.cs
  Services/VnpayService.cs
  appsettings.json
Labels: size/L

#42 Thêm Controller
  Controllers/KhachHangController.cs
  Controllers/NhanVienController.cs
  Controllers/QuanLyChungController.cs
  Controllers/QuanTriVien/QuanTriVienController.cs
  Controllers/QuanTriVien/QuanTriVienPhongController.cs
  Controllers/QuanTriVien/QuanTriVien_HeThongController.cs
  Controllers/QuanTriVien/QuanTriVien_QuanLyDichVuQTVController.cs
  Controllers/QuanTriVien/QuanTriVien_QuanTriNhanVienController.cs
  Controllers/QuanTriVienController.cs
  Controllers/TatCaTruyCapController.cs
  DTOs/HienThiTatCaXem/DichVuDTO.cs
  DTOs/NhanVien/NhanVienThemBaiVietDTO.cs
  DTOs/QuanTriVien/QuanTriVienDuyetBaiVietDTO.cs
  DTOs/QuanTriVien/QuanTriVienThem1DichVuDTO.cs
  DTOs/QuanTriVien/QuanTriVienXoa1Phong.cs
  DTOs/QuanTriVien/QuanTriVienXoa1TienNghiDTO.cs
  DTOs/QuanTriVien/QuanTriVienXoaNhieuTienNghiDTO.cs
  HotelManagementAPI.csproj
  Program.cs
  RoleMiddleware/RoleMiddleware.cs
Labels: size/XXL

#46 Refactor and Update DTOs, Controllers, and Validators
  Controllers/KhachHangController.cs
  Controllers/NhanVienController.cs
  Controllers/QuanLyChungController.cs
  Controllers/QuanTriVienController.cs
  Controllers/TatCaTruyCapController.cs
  Controllers/XacThucController.cs
  DTOs/KhachHang/KhachHangChiTietHoaDon.cs
  DTOs/KhachHang/KhachHangDatDichVuDTO.cs
  DTOs/KhachHang/KhachHangDatPhongDTO.cs
  DTOs/KhachHang/KhachHangFeedBackDTO.cs
  DTOs/KhachHang/KhachHangHoaDonDTO.cs
  DTOs/KhachHang/KhachHangLichSuGiaoDichDTO.cs
  DTOs/KhachHang/KhachHangTaoHoaDonRequestDTO.cs
  DTOs/KhachHang/KhachHangThanhToanDTO.cs
  DTOs/KhachHang/TaoHoaDonRequestDTO.cs
  DTOs/NhanVien/ChiTietBaoCaoDTO.cs
  DTOs/NhanVien/NhanVienSuaPhongAnhPutDTO.cs
  DTOs/NhanVien/NhanVienSuaPhongTienNghiDTO.cs
  DTOs/QuanLyChung/QuanLyChungSuaBaiVietDTO.cs
  DTOs/QuanLyChung/QuanLyChungSuaDichVuDTO.cs
  DTOs/QuanLyChung/QuanLyChungSuaPhongAnhPutDTO.cs
  DTOs/QuanLyChung/QuanLyChungSuaPhongGiamGiaDTO.cs
  DTOs/QuanLyChung/QuanLyChungSuaPhongTienNghiDTO.cs
  DTOs/QuanTriVien/QuanTriVienApDungGiamGiaDTO.cs
  DTOs/QuanTriVien/QuanTriVienThem1PhongDTO.cs
  Validators/HoaDonDTOValidator.cs
  Validators/NguoiDungDTOValidator.cs
  Validators/ThanhToanDTOValidator.cs
Labels: size/XXL

#47 Huy code
  Validators/BaoCaoDTOvalidation.cs
  Validators/ChiTietBaoCaoDTOvalidation.cs
  Validators/DichVuDTOValidator.cs
  Validators/GiamGiaDetailDTOValidator.cs
  Validators/GiamGiaDetailvalidation.cs
  Validators/KhachHangHoaDonDTOvalidation.cs
  Validators/KhachHangThanhToanDTOvalidation.cs
  Validators/NhanVienThemBaiVietDTOvalidation.cs
  Validators/QuanLyChungSuaBaiVietDTOvalidation.cs
  Validators/QuanLyChungSuaDichVuDTOvalidation.cs
  Validators/QuanLyChungSuaPhongAnhPutDTOvalidaton.cs
  Validators/QuanLyChungSuaPhongGiamGiaDTOvalidation.cs
  Validators/QuanLyChungSuaPhongTienNghiDTOvalidation.cs
  Validators/QuanTriVienApDungGiamGiaDTOvalidation.cs
  Validators/QuanTriVienSuaGiamGiaDTOvalidation.cs
  Validators/QuanTriVienSuaNoiQuyDTOvalidation.cs
  Validators/QuanTriVienSuaRoleDTOvalidation.cs
  Validators/QuanTriVienThem1DichVuDTOvalidation.cs
  Validators/QuanTriVienThem1NoiQuyDTOvalidation.cs
  Validators/QuanTriVienThem1PhongDTOvalidation.cs
  Validators/QuanTriVienThem1TienNghiDTOvalidation.cs
  Validators/QuanTriVienThemAnhDTOvalidation.cs
  Validators/QuanTriVienThemGiamGiaDTOvalidation.cs
  Validators/QuanTriVienThemMaGiamGiaDTOvalidation.cs
  Validators/QuanTriVienThemNhieuDichVuvalidation.cs
  Validators/QuanTriVienThemNhieuTienNghiDTOvalidation.cs
  Validators/QuanTriVienXoa1Phongvalidation.cs
  Validators/QuanTriVienXoa1TienNghiDTOvalidation.cs
  Validators/QuanTriVienXoaNhieuTienNghiDTOvalidation.cs
  Validators/QuanTriVienXoaNoiQuyDTOvalidation.cs
  Validators/TaoHoaDonRequestDTOvalidator.cs
  Validators/TatCaBaiVietDTOValidator.cs
  Validators/TienNghiDTOvalidation.cs
Labels: size/XL
