Repository Persinus/HotelManagementAPI, pull requests merged in 2025-05, with the labels that each got.

#12 Integrate Sentiment Analysis and AI Chatbot Features into Hotel Management System
  Controllers/ChatBotSmartController.cs
  Controllers/RoomQueryController.cs
  Controllers/SentimentAnalysisController.cs
  Data/SentimentData.cs
  HotelManagementAPI.csproj
  Program.cs
  TrainML/Program.cs
  TrainML/data.csv
  TrainML/sentimentModel.zip
  appsettings.json
Labels: size/XXL

#13 Update ML.NET
  TrainML/data.csv
  TrainML/sentimentModel.zip
Labels: size/XXL

#15 fix context
  Controllers/TestController.cs
  Program.cs
  appsettings.json
Labels: size/L

#16 Update bài
  Controllers/ChatBotSmartController.cs
  Controllers/DatPhongController.cs
  Controllers/DichvuController.cs
  Controllers/HoaDonDichVuController.cs
  Controllers/HoaDonPhongController.cs
  Controllers/KhachHangController.cs
  Controllers/KhachHangDichVuController.cs
  Controllers/NguoidungController.cs
  Controllers/NhanvienController.cs
  Controllers/PhongController.cs
  Controllers/PhongWithTienNghiController.cs
  Controllers/QuanTriVienController.cs
  Controllers/SentimentAnalysisController.cs
  Controllers/TestController.cs
  Controllers/User_FeatbackController.cs
  FixSwagger.txt
  Helper/HelperJWT.cs
  Models/BaoCao.cs
  Models/ChiTietBaoCao.cs
  Models/ChiTietHoaDon.cs
  Models/DatDichVu.cs
  Models/DatPhong.cs
  Models/DataQlks115Nhom2Context.cs
  Models/DichVu.cs
  Models/Feedback.cs
  Models/GiamGium.cs
  Models/HoaDon.cs
  Models/HoaDonThanhToanDichVu.cs
  Models/HoaDonThanhToanPhong.cs
  Models/KhachHang.cs
  Models/KhachHangDichVu.cs
  Models/KhachHangPhanThuong.cs
  Models/LichSuGiaoDich.cs
  Models/LichSuTinhTrangPhong.cs
  Models/NguoiDung.cs
  Models/NhanVien.cs
  Models/PhanThuong.cs
  Models/Phong.cs
  Models/PhongAnh.cs
  Models/PhongWithTienNghi.cs
  Models/QuanTriVien.cs
  Models/ThanhToan.cs
  Models/TienNghi.cs
  Models/UserFeedback.cs
  Models/VeGiamGium.cs
  Program.cs
  RoleMiddleware/RoleMiddleware.cs
  SQL_Hotel.sql
  appsettings.json
  wwwroot/test.jpg
Labels: size/XXL

#17 sửa bài
  Controllers/NguoidungController.cs
  Controllers/PhongController.cs
  note.txt
Labels: size/L

#18 Cập nhật toàn bộ hệ thống backend quản lý khách sạn để đồng bộ với thay đổi database, models, và thêm tính năng xác thực người dùng.
  Controllers/AuthController.cs
  Controllers/NguoidungController.cs
  Controllers/UserController.cs
  DTOs/DatPhongDTO.cs
  DTOs/HoaDonDTO.cs
  DTOs/LichSuGiaoDich.cs
  DTOs/LoginDTO.cs
  DTOs/NguoiDungDTO.cs
  DTOs/NhanVienDTO.cs
  Helper/HelperJWT.cs
  Models/BaoCao.cs
  Models/ChiTietBaoCao.cs
  Models/ChiTietHoaDon.cs
  Models/DatDichVu.cs
  Models/DatPhong.cs
  Models/DataQlks115Nhom2Context.cs
  Models/DichVu.cs
  Models/Feedback.cs
  Models/GiamGium.cs
  Models/HoaDon.cs
  Models/Hotelnhom2Context.cs
  Models/LichSuGiaoDich.cs
  Models/LichSuTinhTrangPhong.cs
  Models/NguoiDung.cs
  Models/NhanVien.cs
  Models/Phong.cs
  Models/PhongAnh.cs
  Models/ThanhToan.cs
  Models/TienNghi.cs
  Program.cs
  RoleMiddleware/RoleMiddleware.cs
  SQL_Hotel.sql
  note.txt
  obj/Debug/net9.0/HotelManagementAPI.AssemblyInfo.cs
  obj/Debug/net9.0/HotelManagementAPI.AssemblyInfoInputs.cache
  obj/Debug/net9.0/HotelManagementAPI.GeneratedMSBuildEditorConfig.editorconfig
Labels: size/XXL

#19 [Feature] Add role-based controllers: Chung, KhachHang, NhanVien, QuanTriVien
  .gitignore
  Controllers/Chung/AuthController.cs
  Controllers/Chung/DangNhapController.cs
  Controllers/Chung/FeedBackController.cs
  Controllers/Chung/GiamGiaController.cs
  Controllers/Chung/PhongController.cs
  Controllers/KhachHang/DatDichVuController.cs
  Controllers/KhachHang/DatPhongController.cs
  Controllers/KhachHang/HoaDonController.cs
  Controllers/KhachHang/KhachHangController.cs
  Controllers/KhachHang/LichSuGiaoDichController.cs
  Controllers/KhachHang/ThanhToanController.cs
  Controllers/NhanVien/BaoCaoController.cs
  Controllers/NhanVien/DichVuQuanLyController.cs
  Controllers/NhanVien/NhanVienController.cs
  Controllers/NhanVien/PhongQuanLyController.cs
  Controllers/QuanTriVien/HeThongController.cs
  Controllers/QuanTriVien/QuanTriNhanVienController.cs
  Controllers/QuanTriVien/QuanTriVienController.cs
  Controllers/UserController.cs
  Controllers/User_FeatbackController.cs
  RoleMiddleware/RoleMiddleware.cs
  obj/Debug/net9.0/HotelManagementAPI.AssemblyInfo.cs
  obj/Debug/net9.0/HotelManagementAPI.AssemblyInfoInputs.cache
  obj/Debug/net9.0/HotelManagementAPI.GeneratedMSBuildEditorConfig.editorconfig
Labels: size/XL

#20 sửa bài 11/5/2025
  Controllers/AllowAnonymous/AllowAnonymous_LoginController.cs
  Controllers/AllowAnonymous/AllowAnonymous_PhongController.cs
  Controllers/Authorize/Authorize-LogOutController.cs
  Controllers/Chung/AuthController.cs
  Controllers/Chung/PhongController.cs
  Controllers/KhachHang/FeedBackController.cs
  Controllers/KhachHang/KhachHangController.cs
  Controllers/KhachHangController.cs
  Controllers/NguoidungController.cs
  Controllers/NhanVien/GiamGiaController.cs
  Controllers/NhanvienController.cs
  Controllers/PhongController.cs
  Controllers/QuanTriVien/QuanTriVienController.cs
  Controllers/UserController.cs
  DTOs/DatPhongDTO.cs
  DTOs/GiamGiaDTO.cs
  DTOs/LichSuGiaoDichDTO.cs
  DTOs/LoginDTO.cs
  DTOs/NhanVienDTO.cs
  DTOs/PhongDetailsDTO.cs
  DTOs/ResetPasswordDTO.cs
  DTOs/TienNghiDTO.cs
  Data/Hotelnhom2Context.cs
  HotelManagementAPI.csproj
  Models/Feedback.cs
  Models/Hotelnhom2Context.cs
  Models/NguoiDung.cs
  Models/NhanVien.cs
  Program.cs
  RoleMiddleware/RoleMiddleware.cs
Labels: size/XXL

#28 Validation - Bcrypt
  .editorconfig
  Controllers/AllowAnonymous/AllowAnonymous_LoginController.cs
  Controllers/AllowAnonymous/AllowAnoymousDangKyController.cs
  Controllers/Authorize/Authorize-LogOutController.cs
  Controllers/Authorize/Authorize-ProfileController.cs
  Controllers/KhachHang/KhachHangController.cs
  DTOs/LoginDTO.cs
  DTOs/NguoiDungDTO.cs
  DTOs/PhongAnhDTO.cs
  DTOs/PhongDetailsDTO.cs
  DTOs/ResetPasswordDTO.cs
  Helper/SensitiveDataHelper.cs
  HotelManagementAPI.csproj
  Program.cs
  TrainML/data.csv
  Validators/LoginDTOValidator.cs
  Validators/NguoiDungDTOValidator.cs
  Validators/PhongAnhDTOValidator.cs
  Validators/PhongDetailsDTOValidator.cs
  Validators/ResetPasswordDTOValidator.cs
Labels: size/L

#31 fix name controller and deploy let encrypt deploy https
  Controllers/AllowAnonymous/AllowAnonymous_ViewController.cs
  Controllers/AllowAnonymous/AllowAnoymous_DangKyController.cs
  Controllers/Authorize/Authorize_LogOutController.cs
  Controllers/Authorize/Authorize_ProfileController.cs
  Controllers/KhachHang/KhachHang_DatPhongController.cs
  Controllers/KhachHang/KhachHang_FeedBackController.cs
  Controllers/KhachHang/KhachHang_HoaDonController.cs
  Controllers/KhachHang/KhachHang_LichSuGiaoDichController.cs
  Controllers/KhachHang/KhachHang_ThanhToanController.cs
Labels: size/S

#32 Huy
  Controllers/NhanVien/DichVuQuanLyController.cs
  Controllers/NhanVien/GiamGiaController.cs
Labels: size/L
